Features
renercrows/Desktop-Portdolio pull request #1
Opened 2022-06-02 23:16 UTC by renercrows

### Desktop-Portfolio

- Added media queries.
- Added some HTML div tags for background images.
- Added CSS to make its desktop version.

2022-06-03 00:23 UTC, Kossi-stack commented on index.html
> +        <h2 class="subtitle2">My Recent Works</h2>
- [ ] Kindly fix the work section
- Your Design
![Capturedest](https://user-images.githubusercontent.com/81444338/171761350-d311e9e0-53a4-4a15-87fa-b155051a1945.PNG)
- Figma Design
![Capturefdes](https://user-images.githubusercontent.com/81444338/171761653-c5c7a2c8-dbe5-4603-be91-19519dca88ed.PNG)

2022-06-03 00:32 UTC, Kossi-stack commented on index.html
> +                <h2 class="subtitle3">About me</h2>
- [ ] Kindly fix the about me section to look the same as the Figma design
- Your Design
![Capturedesto](https://user-images.githubusercontent.com/81444338/171762027-5ce84f24-97b9-4762-9f08-5063d6e07565.PNG)

- Figma Design
![Capturefide](https://user-images.githubusercontent.com/81444338/171762149-b5f51ccc-f53c-417d-a467-f411466ce2d5.PNG)

2022-06-03 01:22 UTC, keneogu requested changes
Hi @rachidelaid, 

Good job so far!

- All linters are passing
- You are following GitHub flow
- Good commit history
- Good PR description
- Your Design is looking good

There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://media4.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif)

## Required Changes ♻️

- [ ]  Please fix the mobile version requested by the previous reviewer.
your design
![fix_screen](https://user-images.githubusercontent.com/53356820/171768760-8c887598-ff21-490b-8813-068ae60066c3.png)




_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

2022-06-03 18:38 UTC, ShahierNashaat requested changes
Hi @renercrows , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly please fix the mobile version requested by the previous reviewer.
your design
![Screenshot from 2022-06-03 20-37-43](https://user-images.githubusercontent.com/33752735/171926028-9665a4fd-6cec-4479-967e-aef6f9f6030a.png)



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-04 01:04 UTC, renercrows commented
@ShahierNashaat 

Changes were made.

2022-06-04 06:30 UTC, sinansevgi reviewed
Hello @renercrows  👋,

_This is an additional review as a result of the second opinion request._

I can see that the mobile version works as expected. :+1: 

As this was the only reason that your project was not approved it will be **approved** as soon as possible.
Please note that since we will approve it **manually** so this could **take a few hours**!

Keep rocking 🚀!

2022-06-04 17:55 UTC, merged